### ISSUE TITLE
Add itemize.no theming

### ISSUE THREAD

**Issue by kristianvld** [ItemizeNTNU/FusionAuth-Theme#2]
To make integration with https://itemize.no theming should be made more coherent. It would be nice if we could have a design for the FusionAuth theme that looked somewhat like the main website itemize.no.

Not all pages would need theming to begin with, I think we could prioritize the following:
- [x] Login Page (I think this is oauthAuthorize)
- [x] Main front page (index)
- [x] Email templates (depends on #1)
- [x] FavIcon

**Comment by kristianvld** [comment]
@Shirajuki ? :upside_down_face:

**Comment by Shirajuki** [comment]
> @Shirajuki ? 🙃

Hehe, har visst glemt denne repoen helt beklager!
Begynner å få litt mer tid til overs nå, kan begynne å fikse denne ila av denne helgen! ;)

**Comment by kristianvld** [comment]
Ikkje noe stress :sweat_smile: 
Driver å gjør en del opprydding for nye styret og driftansvarlig som skal ta over etter genfors, så prøver å få alt ned på issues og dokumentasjon for tiden :upside_down_face:
