### ISSUE TITLE
Theme all pages

### ISSUE THREAD

**Issue by kristianvld** [ItemizeNTNU/FusionAuth-Theme#5]
Theme all pages to our visual style that users have access to.

Some pages are not accessible by our users, like the User Self Service pages (update profile, 2FA etc), as the User Self Service pages require the FusionAuth Pro license.

It might be that we already have themed all pages that need theming. In which case this issue could be closed.

**Comment by Shirajuki** [comment]
The pages are mostly already themed through the global styling injected to all pages. Some specific pages does however still need some minor detail tweaks I think. I can take a closer look first before closing this issue :)
